<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Main" Id="{b2f2a346-2aab-4873-ae80-3f4daff09e02}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main
VAR
 	fbPowerMaster : FB_PowerMaster;
  fbPowerAxis1 : FB_PowerAxis1;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbPowerMaster();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>