<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{820171f7-8670-42df-9df1-221fdd638619}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbAxisStMachine : FB_AxisStMachineMaster;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbAxisStMachine(AxisInOut := GVL.Axis_Virtual);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>